language: scala
scala:
- 2.10.0
script: sbt clean test
jdk:
- oraclejdk7
env:
- SBT_OPTS="-XX:PermSize=512M -XX:MaxPermSize=1024M"
notifications:
  email:
    on_success: never
    on_failure: change
  hipchat:
    rooms:
      secure: mnqbGUoVeck37BoxFHHL95hEx0vynSbBhLYnftyyPhe6it+xPBzeh0oW/AEste9OG+JiF7ee1E0rDN/R+SxCm7/czm+kSlh4ERb9mFk1k7njUCjk2rfqk+8/o10eAwUj2ksQ69zl7RelMtY5riFyjOpg7ilCAjUEq1z1A5xwCmE=
    template:
    - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
