language: scala
scala:
   - 2.10.0
script: sbt clean test
notifications:
  email:
    on_success: never
    on_failure: change
jdk:
  - oraclejdk7
env:
  - SBT_OPTS="-XX:PermSize=256M -XX:MaxPermSize=512M"
